# Generated by Django 4.0.3 on 2022-05-08 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kurs_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='matn',
            field=models.TextField(default='zur'),
        ),
        migrations.AlterField(
            model_name='course',
            name='daraja',
            field=models.CharField(choices=[('Easy', 'Easy'), ('Hard', 'Hard'), ('Medium', 'Medium')], max_length=15),
        ),
    ]
